# this is the reference file
target1:
	target1 contents
    testing second line
target2 : target1
    target 2a contents
	target 2 contents
 abc
# this is target 3
target3:
	target 3 contents

.PHONY: target1

