#!/usr/bin/env sh

# checking if any "fixable" file was staged
if [[ git diff --name-only --cached | grep -E "\.(ts|js|jsx|tsx|json)$" ]]; then
    echo "Running make lint-fix..."
    make lint-fix
    echo "lint-fix finished"
else
    echo "Skipping lint-fix"
fi
